# Generated by Django 5.0.6 on 2024-06-18 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grouping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code', models.CharField(max_length=64, verbose_name='分组编号')),
                ('group_name', models.CharField(max_length=64, verbose_name='分组名称')),
                ('leader_name', models.CharField(max_length=64, verbose_name='组长姓名')),
                ('desc', models.TextField(max_length=128, verbose_name='更多信息')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(max_length=64, verbose_name='版本名称')),
                ('desc', models.TextField(max_length=128, verbose_name='版本描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(max_length=64, unique=True, verbose_name='用户编号')),
                ('user_name', models.CharField(max_length=64, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, unique=True, verbose_name='密码')),
                ('nickname', models.CharField(max_length=64, unique=True, verbose_name='用户昵称')),
                ('role', models.SmallIntegerField(choices=[(1, '普通用户'), (2, '组长'), (3, '部门主管'), (4, '管理员'), (5, '超级管理员')], default=1, verbose_name='角色身份')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.grouping', verbose_name='所属分组')),
            ],
        ),
    ]
