# Generated by Django 5.0.6 on 2024-06-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_user_user_head_alter_user_nickname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouping',
            name='desc',
            field=models.TextField(blank=True, max_length=128, verbose_name='更多信息'),
        ),
    ]
