# Generated by Django 5.0.6 on 2024-06-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0003_alter_grouping_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouping',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='grouping',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='user',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='version',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='version',
            name='update_time',
        ),
        migrations.AlterField(
            model_name='grouping',
            name='create_time',
            field=models.DateTimeField(verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='grouping',
            name='desc',
            field=models.CharField(blank=True, max_length=128, verbose_name='更多信息'),
        ),
    ]
