# Generated by Django 5.0.6 on 2024-06-20 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0004_remove_grouping_is_delete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouping',
            name='create_time',
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='version',
            name='create_time',
            field=models.DateTimeField(verbose_name='创建时间'),
        ),
    ]
