# Generated by Django 5.0.6 on 2024-06-20 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0005_remove_grouping_create_time_alter_user_create_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouping',
            name='create_time',
            field=models.DateTimeField(default='1999-01-01', verbose_name='创建时间'),
            preserve_default=False,
        ),
    ]
